-- AlterTable
ALTER TABLE "Pedido" ALTER COLUMN "Ordem de carga" DROP NOT NULL,
ALTER COLUMN "Previsão de entrega" DROP NOT NULL,
ALTER COLUMN "Controle" DROP NOT NULL,
ALTER COLUMN "PREVISÃO ENTREGA" DROP NOT NULL;
